### ISSUE TITLE
Removing your FL username doesn't remove the FL badge from your profile

### ISSUE THREAD

**Issue by spilth** [BDSMorg/frontseat#21]
Steps to recreate:

- Go to https://bdsm.org/settings/connections
- Remove your FL username
- Click Save Changes
- Navigate to your Profile page

Expected: Profile page should no longer have an FL badge
Actual: Profile has FL badge that links to root of FL

**Comment by Daddy** [comment]
This has now been fixed. Thank you for the report @spilth!
